 //! ...
LinkedList();  // construtor padrão
//! ...
~LinkedList();  // destrutor
//! ...
void clear();  // limpar lista
//! ...
void push_back(const T& data);  // inserir no fim
//! ...
void push_front(const T& data);  // inserir no início
//! ...
void insert(const T& data, std::size_t index);  // inserir na posição
//! ...
void insert_sorted(const T& data);  // inserir em ordem
//! ...
T& at(std::size_t index);  // acessar um elemento na posição index
//! ...
T pop(std::size_t index);  // retirar da posição
//! ...
T pop_back();  // retirar do fim
//! ...
T pop_front();  // retirar do início
//! ...
void remove(const T& data);  // remover específico
//! ...
bool empty() const;  // lista vazia
//! ...
bool contains(const T& data) const;  // contém
//! ...
std::size_t find(const T& data) const;  // posição do dado
//! ...
std::size_t size() const;  // tamanho da lista